apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htmf
  template:
    metadata:
      labels:
        app: htmf
    spec:
      containers:
      - name: htmf
        image: mainframe-v0
        imagePullPolicy: Never
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8000
