apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain #Recycle
  hostPath:
    path: "/var/jenkins/mainframe"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # volumeMode: Filesystem
  

  # storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2


# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jenkins-pv
#   namespace: sybrenbolandit
# spec:
#   storageClassName: jenkins-pv
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 20Gi
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: /data/jenkins-volume/


#jenkins deployment yaml
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: jenkins
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: jenkins
#   template:
#     metadata:
#       labels:
#         app: jenkins
#     spec:
#       containers:
#       - name: jenkins
#         image: jenkins/jenkins:lts-jdk11
#         ports:
#         - containerPort: 8080
#         volumeMounts:
#         - name: jenkins-home
#           mountPath: /var/jenkins_home
#       volumes:
#       - name: jenkins-home
#         emptyDir: { }

#jenkins service yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins
# spec:
#   type: NodePort
#   ports:
#   - port: 8080
#     targetPort: 8080
#   selector:
#     app: jenkins