apiVersion: v1
kind: Service
metadata:
  name: mf-service
spec:
  #type: NodePort
  selector:
    app: mf
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    #nodePort: 31000
---
apiVersion: v1
kind: Service
metadata:
  name: mf-jenkins-service
spec:
  #type: NodePort
  selector:
    app: mf-jenkins
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080