apiVersion: v1
kind: Service
metadata:
  name: mf-service
spec:
  type: NodePort
  selector:
    app: mf
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: mf-jenkins-service
spec:
  type: NodePort
  selector:
    app: mf-jenkins
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8080
    nodePort: 32000