# Generated by Django 4.2.1 on 2024-03-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=12)),
                ('end', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('val', models.IntegerField()),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DepreciationAndAmortization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=12)),
                ('end', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('val', models.IntegerField()),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dividends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=12)),
                ('end', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('perShare', models.FloatField()),
                ('totalPaid', models.IntegerField()),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=12)),
                ('end', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('val', models.FloatField()),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GainLossSaleProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=12)),
                ('end', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('val', models.IntegerField()),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InterestPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=12)),
                ('end', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('val', models.IntegerField()),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NetCashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=12)),
                ('end', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('val', models.IntegerField()),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingCashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=12)),
                ('end', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('val', models.IntegerField()),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=12)),
                ('end', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('val', models.IntegerField()),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=12)),
                ('end', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('val', models.IntegerField()),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SharesOutstanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=12)),
                ('end', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('val', models.IntegerField()),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=12)),
                ('end', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('val', models.FloatField()),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TotalDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=12)),
                ('end', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('val', models.IntegerField()),
                ('shortTermDebt', models.IntegerField()),
                ('longTermDebt1', models.IntegerField()),
                ('longTermDebt2', models.IntegerField()),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TotalEquity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=12)),
                ('end', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('val', models.IntegerField()),
                ('totalAssets', models.IntegerField()),
                ('totalLiabilities', models.IntegerField()),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10)),
            ],
        ),
    ]
