# Generated by Django 4.2.1 on 2024-03-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dividends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=12)),
                ('end', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('interestPaid', models.IntegerField()),
                ('divsPaidPerShare', models.FloatField()),
                ('totalDivsPaid', models.IntegerField()),
                ('shares', models.IntegerField()),
                ('sharesGrowthRate', models.FloatField()),
                ('divGrowthRate', models.FloatField()),
                ('integrityFlag', models.CharField(max_length=10)),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Dividends',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=12)),
                ('end', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('revenue', models.IntegerField()),
                ('revGrowthRate', models.FloatField()),
                ('netIncome', models.IntegerField()),
                ('netIncomeGrowthRate', models.FloatField()),
                ('operatingCashFlow', models.IntegerField()),
                ('operatingCashFlowGrowthRate', models.FloatField()),
                ('netCashFlow', models.IntegerField()),
                ('netCashFlowGrowthRate', models.FloatField()),
                ('capEx', models.IntegerField()),
                ('fcf', models.IntegerField()),
                ('fcfGrowthRate', models.FloatField()),
                ('fcfMargin', models.FloatField()),
                ('fcfMarginGrowthRate', models.FloatField()),
                ('eps', models.IntegerField()),
                ('epsGrowthRate', models.FloatField()),
                ('depreNAmor', models.IntegerField()),
                ('gainSaleProp', models.IntegerField()),
                ('ffo', models.IntegerField()),
                ('ffoGrowthRate', models.FloatField()),
                ('integrityFlag', models.CharField(max_length=10)),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Income',
            },
        ),
        migrations.CreateModel(
            name='ROIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=12)),
                ('end', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('operatingIncome', models.IntegerField()),
                ('operatingIncomeGrowthRate', models.FloatField()),
                ('taxRate', models.FloatField()),
                ('TotalDebt', models.IntegerField()),
                ('assets', models.IntegerField()),
                ('liabilities', models.IntegerField()),
                ('TotalEquity', models.IntegerField()),
                ('nopat', models.IntegerField()),
                ('investedCapital', models.IntegerField()),
                ('roic', models.FloatField()),
                ('ticker', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ROIC',
            },
        ),
    ]
