# Generated by Django 4.2.11 on 2024-05-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mega',
            name='ReportedTotalEquityGrowthRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mega',
            name='TotalDebtGrowthRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mega',
            name='TotalEquityGrowthRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mega',
            name='dilutedSharesGrowthRate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
