# Generated by Django 4.2.1 on 2024-03-02 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='capex',
            table='CapEx',
        ),
        migrations.AlterModelTable(
            name='depreciationandamortization',
            table='DepNAmor',
        ),
        migrations.AlterModelTable(
            name='dividends',
            table='Dividends',
        ),
        migrations.AlterModelTable(
            name='eps',
            table='EPS',
        ),
        migrations.AlterModelTable(
            name='gainlosssaleproperty',
            table='GainPropSales',
        ),
        migrations.AlterModelTable(
            name='interestpaid',
            table='InterestPaid',
        ),
        migrations.AlterModelTable(
            name='netcashflow',
            table='NetCashFlow',
        ),
        migrations.AlterModelTable(
            name='operatingcashflow',
            table='OperatingCashFlow',
        ),
        migrations.AlterModelTable(
            name='operatingincome',
            table='OperatingIncome',
        ),
        migrations.AlterModelTable(
            name='revenue',
            table='Revenue',
        ),
        migrations.AlterModelTable(
            name='sharesoutstanding',
            table='SharesOutstanding',
        ),
        migrations.AlterModelTable(
            name='taxrate',
            table='TaxRate',
        ),
        migrations.AlterModelTable(
            name='totaldebt',
            table='TotalDebt',
        ),
        migrations.AlterModelTable(
            name='totalequity',
            table='TotalEquity',
        ),
    ]
