# Generated by Django 4.2.11 on 2024-06-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor_center', '0005_metadata_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='cepsAVG',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='cepsAVGintegrity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='cepsAVGnz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='cepsGrowthAVG',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='cepsGrowthAVGintegrity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='cepsGrowthAVGnz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='cepsLow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='reitepsAVG',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='reitepsAVGintegrity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='reitepsAVGnz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='reitepsGrowthAVG',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='reitepsGrowthAVGintegrity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='reitepsGrowthAVGnz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='reitepsLow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='repsAVG',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='repsAVGintegrity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='repsAVGnz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='repsGrowthAVG',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='repsGrowthAVGintegrity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='repsGrowthAVGnz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='repsLow',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
