# Generated by Django 4.2.11 on 2024-06-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor_center', '0009_investable_universe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='REITFullWeight_Ranking',
        ),
    ]
