# Generated by Django 4.2.11 on 2024-06-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor_center', '0010_delete_reitfullweight_ranking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullWeight_Ranking',
        ),
    ]
