# Generated by Django 4.2.11 on 2024-07-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor_center', '0013_divgrowth_ranking_maxplainscore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(max_length=10)),
                ('CIK', models.IntegerField(blank=True, null=True)),
                ('Sector', models.CharField(max_length=30)),
                ('Industry', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stockList',
            },
        ),
        migrations.DeleteModel(
            name='Metadata_Backup',
        ),
    ]
