# Generated by Django 4.2.12 on 2024-07-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor_center', '0014_stocklist_delete_metadata_backup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(blank=True, max_length=10, null=True)),
                ('Sector', models.CharField(blank=True, max_length=5, null=True)),
                ('currentPrice', models.FloatField(blank=True, null=True)),
                ('currentDiv', models.FloatField(blank=True, null=True)),
                ('currentValuation', models.FloatField(blank=True, null=True)),
                ('priceGR', models.FloatField(blank=True, null=True)),
                ('divGR', models.FloatField(blank=True, null=True)),
                ('tenYearPrice', models.FloatField(blank=True, null=True)),
                ('tenYearDiv', models.FloatField(blank=True, null=True)),
                ('tenYearValuation', models.FloatField(blank=True, null=True)),
                ('twentyYearPrice', models.FloatField(blank=True, null=True)),
                ('twentyYearDiv', models.FloatField(blank=True, null=True)),
                ('twentyYearValuation', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PDValuation',
            },
        ),
    ]
