# Generated by Django 4.2.12 on 2024-07-19 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor_center', '0015_pdvaluation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDValuation',
        ),
    ]
