# Generated by Django 4.2.12 on 2024-07-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor_center', '0016_delete_pdvaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector_rankings',
            name='scorerank',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
