# Generated by Django 4.2.12 on 2024-07-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor_center', '0017_sector_rankings_scorerank'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate_ranking',
            name='reitroce',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sector_rankings',
            name='reitroce',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
