# Generated by Django 4.2.12 on 2024-08-01 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor_center', '0019_bdc_ranking_metadata_backup_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BDC_Ranking',
        ),
        migrations.DeleteModel(
            name='Communications_Ranking',
        ),
        migrations.DeleteModel(
            name='ConsumerCyclical_Ranking',
        ),
        migrations.DeleteModel(
            name='ConsumerDefensive_Ranking',
        ),
        migrations.DeleteModel(
            name='DivGrowth_Ranking',
        ),
        migrations.DeleteModel(
            name='Energy_Ranking',
        ),
        migrations.DeleteModel(
            name='Financials_Ranking',
        ),
        migrations.DeleteModel(
            name='Growth_Ranking',
        ),
        migrations.DeleteModel(
            name='Healthcare_Ranking',
        ),
        migrations.DeleteModel(
            name='Industrials_Ranking',
        ),
        migrations.DeleteModel(
            name='Investable_Universe',
        ),
        migrations.DeleteModel(
            name='Materials_Ranking',
        ),
        migrations.DeleteModel(
            name='QualNonDivPayers_Ranking',
        ),
        migrations.DeleteModel(
            name='RealEstate_Ranking',
        ),
        migrations.DeleteModel(
            name='Tech_Ranking',
        ),
        migrations.DeleteModel(
            name='Utilities_Ranking',
        ),
    ]
