# Generated by Django 4.2.12 on 2024-08-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor_center', '0020_delete_bdc_ranking_delete_communications_ranking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector_Rankings2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(blank=True, max_length=10, null=True)),
                ('Sector', models.CharField(blank=True, max_length=5, null=True)),
                ('reitroce', models.IntegerField(blank=True, null=True)),
                ('roce', models.IntegerField(blank=True, null=True)),
                ('roic', models.IntegerField(blank=True, null=True)),
                ('roc', models.IntegerField(blank=True, null=True)),
                ('ffopo', models.IntegerField(blank=True, null=True)),
                ('po', models.IntegerField(blank=True, null=True)),
                ('divgr', models.IntegerField(blank=True, null=True)),
                ('divpay', models.IntegerField(blank=True, null=True)),
                ('shares', models.IntegerField(blank=True, null=True)),
                ('cf', models.IntegerField(blank=True, null=True)),
                ('bv', models.IntegerField(blank=True, null=True)),
                ('equity', models.IntegerField(blank=True, null=True)),
                ('debt', models.IntegerField(blank=True, null=True)),
                ('fcfm', models.IntegerField(blank=True, null=True)),
                ('fcf', models.IntegerField(blank=True, null=True)),
                ('ffo', models.IntegerField(blank=True, null=True)),
                ('ni', models.IntegerField(blank=True, null=True)),
                ('rev', models.IntegerField(blank=True, null=True)),
                ('divyield', models.IntegerField(blank=True, null=True)),
                ('maxscore', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('scorerank', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Sector_Rankings2',
            },
        ),
    ]
