name: Deploy to Lightsail

env:
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #Checkout
      - name: Checkout Repo
        uses: actions/checkout@v3

      #Setup SSH
      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh

      #Suggested Industry Standard Edits to the above
      # - name: Set up SSH Key
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.LS_SSH_KEY }}
          
      #Update Known Hosts
      - name: Add Server to Known Hosts
        run: ssh-keyscan -H investmenthighlights.com >> ~/.ssh/known_hosts
      
      #Build Docker & NGINX Images
      - name: Build Docker Images
        run: |
          docker build -t djangonwt:latest ./
          docker build -t nginxdj:latest ./mainframe/nginx/

      #Suggested Industry Standard Edits to the above
      # - name: Build Docker Images
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./
      #     tags: djangonwt:latest
          #repeat for NGINX

      #Roll images into tarballs!
      - name: Create Docker Image tarballs
        run: |
          docker save djangonwt:latest > django.tar
          docker save nginxdj:latest > nginx.tar

      # SCP Tarballs to Lightsail
      - name: SCP Docker Image Tarballs and DC.yaml
        run: |
          scp -i ~/.ssh/id_rsa django.tar ubuntu@investmenthighlights.com:/home/ubuntu/
          scp -i ~/.ssh/id_rsa nginx.tar ubuntu@investmenthighlights.com:/home/ubuntu/
          scp -i ~/.ssh/id_rsa ./docker-compose.yaml ubuntu@investmenthighlights.com:/home/ubuntu/

      #SSH into Lightsail, Manage Docker
      - name: SSH into Lightsail, Restart App
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@investmenthighlights.com << EOF
            sudo docker-compose down
            sudo docker rmi djangonwt:latest || true
            sudo docker rmi nginxdj:latest || true
            sudo docker load < django.tar
            sudo docker load < nginx.tar
            sudo docker-compose up -d
          EOF