name: Deploy to Lightsail

env:
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches:
      - prod #Only push updates when prod branch merged/updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #Checkout
      - name: Checkout Repo
        uses: actions/checkout@v3

      #Setup SSH
      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh

      # #Debug Key File; deprecated after successfully debugged
      # - name: Debug Key File
      #   run: |
      #     head -n 5 ~/.ssh/id_rsa
      #     tail -n 5 ~/.ssh/id_rsa
          
      #Update Known Hosts
      - name: Add Server to Known Hosts
        run: ssh-keyscan -H investmenthighlights.com >> ~/.ssh/known_hosts #54.186.31.9
      
      #Build Docker & NGINX Images
      - name: Build Docker Images
        run: |
          docker build -t djangonwt:latest ./
          docker build -t nginxdj:latest ./nginx/

      #Roll images into tarballs!
      - name: Create Docker Image tarballs
        run: |
          docker save djangonwt:latest > django.tar
          docker save nginxdj:latest > nginx.tar

      #Build NGINX Image
      # - name: Build NGINX Image
      #   run: docker build -t nginxdj:latest ./nginx/

      #Roll that image into a tarball!
      # - name: Create NGINX Image tarball
      #   run: docker save nginxdj:latest > nginx.tar

      #Test Connection to Lightsail; deprecated after successfully debugged
      # - name: Test SSH Connection
      #   run: ssh -v -i ~/.ssh/id_rsa ubuntu@54.186.31.9 'echo Connection Successful!'

      # SCP Tarballs to Lightsail
      - name: SCP Docker Image Tarballs
        run: |
          scp -i ~/.ssh/id_rsa django.tar ubuntu@investmenthighlights.com:/home/ubuntu/
          scp -i ~/.ssh/id_rsa nginx.tar ubuntu@investmenthighlights.com:/home/ubuntu/

      #SSH into Lightsail, Manage Docker
      - name: SSH into Lightsail, Restart App
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@investmenthighlights.com << EOF
            sudo docker-compose down
            sudo docker rmi djangonwt:latest || true
            sudo docker rmi nginxdj:latest || true
            sudo docker load < django.tar
            sudo docker load < nginx.tar
            sudo docker-compose up -d
          EOF